server.port=8080
management.endpoints.web.exposure.include=*
spring.cloud.gateway.discovery.locator.enabled=true

# --- ms-planes ---
spring.cloud.gateway.routes[0].id=ms-planes
spring.cloud.gateway.routes[0].uri=http://comunet-planes:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/ms-planes/**
spring.cloud.gateway.routes[0].filters[0].name=AuthenticationFilter
spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=planesCB
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/planes
spring.cloud.gateway.routes[0].filters[2].name=StripPrefix
spring.cloud.gateway.routes[0].filters[2].args._genkey_0=1
springdoc.swagger-ui.urls[0].name=Cobertura
springdoc.swagger-ui.urls[0].url=/ms-cobertura/v3/api-docs


# --- ms-usuarios ---
spring.cloud.gateway.routes[1].id=ms-usuarios
spring.cloud.gateway.routes[1].uri=http://comunet-usuarios:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/ms-usuarios/**
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=usuariosCB
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/usuarios
spring.cloud.gateway.routes[1].filters[1].name=StripPrefix
spring.cloud.gateway.routes[1].filters[1].args._genkey_0=1
springdoc.swagger-ui.urls[1].name=Usuarios
springdoc.swagger-ui.urls[1].url=/ms-usuarios/v3/api-docs

# --- ms-contacto ---
spring.cloud.gateway.routes[2].id=ms-contacto
spring.cloud.gateway.routes[2].uri=http://comunet-contacto:8080
spring.cloud.gateway.routes[2].predicates[0]=Path=/ms-contacto/**
spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=contactoCB
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/contacto
spring.cloud.gateway.routes[2].filters[1].name=StripPrefix
spring.cloud.gateway.routes[2].filters[1].args._genkey_0=1
springdoc.swagger-ui.urls[2].name=Planes
springdoc.swagger-ui.urls[2].url=/ms-planes/v3/api-docs

# --- ms-cobertura ---
spring.cloud.gateway.routes[3].id=ms-cobertura
spring.cloud.gateway.routes[3].uri=http://comunet-cobertura:8080
spring.cloud.gateway.routes[3].predicates[0]=Path=/ms-cobertura/**
spring.cloud.gateway.routes[3].filters[0].name=AuthenticationFilter
spring.cloud.gateway.routes[3].filters[1].name=StripPrefix
spring.cloud.gateway.routes[3].filters[1].args._genkey_0=1
spring.cloud.gateway.routes[3].filters[2].name=CircuitBreaker
spring.cloud.gateway.routes[3].filters[2].args.name=coberturaCB
spring.cloud.gateway.routes[3].filters[2].args.fallbackUri=forward:/fallback/cobertura
springdoc.swagger-ui.urls[3].name=Contacto
springdoc.swagger-ui.urls[3].url=/ms-contacto/v3/api-docs



