server.port=8080
management.endpoints.web.exposure.include=*
spring.cloud.gateway.discovery.locator.enabled=true

# Ruta para ms-planes (Puerto 8081)
spring.cloud.gateway.routes[0].id=ms-planes
spring.cloud.gateway.routes[0].uri=http://ms-planes:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/ms-planes/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Ruta para ms-usuarios (Puerto 8083)
spring.cloud.gateway.routes[1].id=ms-usuarios
spring.cloud.gateway.routes[1].uri=http://ms-usuarios:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/ms-usuarios/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Ruta para ms-contacto (Puerto 8082)
spring.cloud.gateway.routes[2].id=ms-contacto
spring.cloud.gateway.routes[2].uri=http://ms-contacto:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/ms-contacto/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Ruta para ms-cobertura (Puerto 8084)
spring.cloud.gateway.routes[3].id=ms-cobertura
spring.cloud.gateway.routes[3].uri=http://ms-cobertura:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/ms-cobertura/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1