server.port=8080
mensaje.prueba=Configuración desde el Server para Planes

# BASE DE DATOS (Usando el nombre del contenedor para Docker)
spring.datasource.url=jdbc:postgresql://comunet-postgres:5432/db_planes
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FLYWAY (Migrado del local al server)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration

# RESILIENCE4J - CIRCUIT BREAKER
# Nota: Asegúrate de que en tu Java uses @CircuitBreaker(name = "coberturaCB")
resilience4j.circuitbreaker.instances.coberturaCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.coberturaCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.coberturaCB.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.coberturaCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.coberturaCB.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.coberturaCB.permitted-number-of-calls-in-half-open-state=2

# RESILIENCE4J - TIME LIMITER
resilience4j.timelimiter.instances.coberturaCB.timeout-duration=2s