-- 1. Tabla Maestra: municipios_colombia
CREATE TABLE IF NOT EXISTS municipios_colombia (
                                                   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                   departamento VARCHAR(255),
    nombre VARCHAR(255),
    tecnologia VARCHAR(255)
    );

-- 2. Tabla Operativa: coberturas
CREATE TABLE IF NOT EXISTS coberturas (
                                          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                          tecnologia VARCHAR(255),
    municipio_id BIGINT,
    -- Definición de la relación que vimos en el ERD
    CONSTRAINT fk_municipio_cobertura
    FOREIGN KEY (municipio_id)
    REFERENCES municipios_colombia (id)
    );